### ISSUE TITLE
Identify New Test Projects

### ISSUE THREAD

**Issue by g-goulis** [cloudhubs/cimet2#29]
**We need additional test projects to validate tool, identify the current status of each.**

- [ ] https://github.com/apolloconfig/apollo

- [ ] https://github.com/hoangtien2k3/ecommerce-microservices

- [ ] https://github.com/thingsboard/thingsboard

- [ ] https://github.com/corona-warn-app/cwa-server

- [ ] https://github.com/AthirsonSilva/spring-microservices

- [ ] https://github.com/nashtech-garage/yas

- [ ] https://github.com/tmobile/pacbot

- [ ] https://github.com/piomin/sample-spring-microservices-new

**Comment by samnperry** [comment]
apollo: 
![Screenshot 2024-09-10 204754](https://github.com/user-attachments/assets/1a33e7fe-50af-4308-89b9-c7123c4dc7c4)
ecommerce_microservices: Program starts but then ends with no message or IR.
cwa-server: Produced a valid IR
pacbot: Produced a valid IR
sample-spring-microservices-new: Produced a valid IR
spring-microservices: Produced a valid IR
thingsboard:  Program starts but then ends with no message or IR.
yas: Program starts but then ends with no message or IR.
