### ISSUE TITLE
`WrongCuts` implementation

### ISSUE THREAD

**Issue by bakhtos** [cloudhubs/cimet2#9]
@samnperry 
After examining the `WrongCuts` antipattern implementation with Tomas, we came to the conclusion that it cannot be identified using the DFS walk over the Service Dependency Graph since the anti-pattern is about how frontend/backend parts are divided between services.

Please discuss with Tomas how to create a new implementation.

**Comment by samnperry** [comment]
Fixed it to look for an empty list of repository classes in each microservices based on Cerny's suggestion.
